---
date: "2016-12-14T00:00:00Z"
external_link: ""
image:
  caption: Photo by mpho-mojapelo on Unsplash
  focal_point: Smart
#links:
#- icon: github
#  icon_pack: fab
#  name: Github
#  url: https://twitter.com/georgecushen
#slides: example
summary: Implementation of Lean methodologies in the Emergency Department of a hospital
#tags:
#- Deep Learning
title: Managing the Lean Enterprise Improvement Program
#url_code: ""
#url_pdf: ""
#url_slides: ""
#url_video: ""
---
<span style="font-size: medium;">The emergency department (ED) of a hospital is the most critical unit in the medical field. In a world of unpredictable endemics and pandemics, it is of utmost importance for EDs to have the best layout to treat patients effectively on time. Patient dissatisfaction and health-related potential risk situations in the ED are inevitable if the flow of patients through the various stages of medical treatment is not managed properly. Application of Lean methodologies, thus, has become significantly important in improving the effectiveness of ED operations. Using the concepts of Value Stream Mapping and Kaizen, ED processes can be improved to handle issues such as insufficient capacity or inefficient resource utilization.</span>  
<span style="font-size: medium;">Several research papers showcase studies conducted on the application of Lean principles in the healthcare sector and how it has led to the optimization of the internal processes in EDs. These papers have been able to suggest methods that have added value to the operational activities of the EDs. Various research endeavors have also pinpointed the underlying factors that contribute to inefficiencies in the ED processing area. Some of these factors include non-value-adding activities like waiting for a vacant in-patient bed, a consultation reply, or a radiology request to be executed (Elamir, H.,2018). At times, the absence of established protocols during ED procedures has been noted to prolong patient wait times, increase the likelihood of medical errors, and result in unnecessary task repetition (Kabirinaeini et al., 2023).</span>  
<span style="font-size: medium;">According to a recent study by Kabirinaeini et al. (2023), inefficiencies in hospitals stem from the wasteful use of resources and facilities. Implementing lean management principles can cut down waste across various hospital dimensions, including inventory, waiting times, processes, and services. Hence, they came up with a 6-step model, based on the Deming cycle, for implementing lean management in the ED – the framework included a central core (enablers) and a recurring cycle with six activities, addressing different wastes in each iteration. Notably, the model emphasized planning, goal-setting, resource allocation, and using lean tools to identify waste sources. It also involved analyzing processes, identifying losses, monitoring the implementation process, and addressing issues like waiting time, inventory waste, and errors.</span> 
<span style="font-size: medium;">Souza et al. (2021) conducted a six-step systematic review which revealed that various ED research problems such as long waiting times, long hospital stays, health safety, poor resource management, and high patient flow were consistently addressed through Lean initiatives and had positive benefits. They also emphasized the significance of cultivating Kaizen – a culture of continuous improvement, and the need for training multidisciplinary team members in Lean concepts and tools.</span>
<span style="font-size: medium;">Kaizen, though challenging, helps in generating ideas for enhancing the overall ED efficiency. Research conducted by Uppal et al. (2012) highlights the essential requirement for ongoing enhancements to guarantee quality patient care. Their team pinpointed the process issues in a newly established community hospital ED, generated solutions, and implemented changes which further led to a 50% reduction in discharge time for patients.</span>  
  
**PROBLEM STATEMENT**  
<span style="font-size: medium;">Abeidi et al. (2018), through their study, collected real-life data on the length of stay of patients in the ED of a hospital in Istanbul, Turkey. In addition, they interviewed healthcare professionals and management personnel at the hospital. Their study specifically concentrated on patients necessitating immediate intervention whose conditions had the potential to escalate into life-threatening situations (Level 2-3 patients, as per Triage classification). Using the data collected, they came up with the current state VSM of the ED and successfully developed a simulation model that closely mirrored the characteristics of the actual system. After analyzing the root causes of the value and non-value-added activities, and considering the areas of improvement, they successfully developed a prospective VSM for the ED process design. Implementation of this design could potentially decrease patients' length of stay from 86.14 to 60.15 minutes. However, their study did not identify potential bottlenecks within the ED system. Rather than overhauling the entire ED process, an alternative approach involved pinpointing specific processes that contributed to overall patient length of stay. Comprehending the underlying reasons for the prolonged duration of the bottleneck process and employing lean techniques to address them could also aid in establishing a streamlined flow for the entire ED.</span>
  
**OBJECTIVES**  
<span style="font-size: medium;">This project focuses on performing discrete event simulations using SIMIO software by creating a model as per the current state VSM layout from Abeidi et al. (2018), for Level 2-3 patients in the ED. After simulating the model for 300 hours, (which equals the length of Abeidi et al.’s (2018) study that was conducted for 2 months, between 11:30 AM to 4:00 PM), the different data parameters obtained were analyzed and the possible bottleneck process was identified. To deal with the said bottleneck, three different scenarios were considered. In the first scenario, the capacity of the medical staff was increased. In the second scenario, without considering the need for additional resources or capacity, the non-value-added activities were removed for all the processes. The third scenario was a combination of the first two scenarios - the staff capacity was increased for the bottleneck process and non-value-added time for the processes was not considered. The outcomes of these three scenarios were assessed for comparison, and optimal process parameters were proposed to enhance the ED's efficiency, specifically for Level 2-3 patients. Furthermore, recommendations were provided to explore various lean techniques that can be implemented in the ED, aimed at improving effectiveness in delivering services promptly and attentively.</span>  
  
**METHODS**  
<span style="font-size: medium;">The core principles of Lean thinking – understanding the specific needs and preferences of the patients, visualizing the flow of patients, information, and materials, creating a smooth and uninterrupted flow of patients, providing care and services based on actual patient demand, and fostering a culture of continuous improvement – can help in reducing different forms of wastes generated in the healthcare unit. Pure waste, such as procuring more medical supplies leading to excess inventory, long patient waiting times for appointments or test results, unnecessary movement of patients, staff, or medical equipments, and performing redundant tests on patients, do not add any value. Necessary waste, like scheduled maintenance of medical equipment or facilities to ensure their continued functionality and safety, maintaining safety buffers to handle unexpected surges in patient volume as well as implementing checks and verifications to reduce the risk of serious errors, also do not add direct value for the patients. However, they indirectly add value through the overall service delivered by the healthcare unit. To provide improvement initiatives for the ED environment, the methodology adopted in this study took into consideration the five principles of Lean toward increasing the value-added activities, minimizing the necessary non-value-added activities to an extent where a minimal number of resources are required, and eliminating the non-essential non-value-added activities.</span>  
  
<span style="font-size: medium;">SIMULATION-BASED VALUE STREAM MAPPING</span>  
<span style="font-size: medium;">Level 2-3 patients in the ED need to go through, roughly, the same processes for treatment. Hence, a VSM is essential to visualize the entire flow. On the other hand, simulation allows for a more comprehensive understanding, by considering the dynamic aspects and interactions within the system. This study incorporated the qualitative and visualizing method of VSM in conjunction with the quantitative analysis of simulation to identify the bottlenecks, inefficiencies, and areas for improvement in the ED. This approach also leaves open the possibility of assessing the potential impact of changes and identifying any unintended consequences, before implementing the proposed lean techniques for process modifications in the actual ED environment. A simulation model was thus created based on the current state of VSM available. The quantitative data obtained, after the model simulation, was used to conduct a thorough analysis of the average flow time, resource utilization, average waiting time in queue, and throughput of the different processes within the ED, to pinpoint and address the bottleneck.</span>  
  
**DATA COLLECTION AND ANALYSIS**  
<span style="font-size: medium;">Data for this project was obtained from the research work conducted by Abeidi et al. (2018) in the ED of a hospital in Turkey. Through direct observation, they collected data about the time consumed by patients for different medical procedures within the ED. Based on their data, the cycle time, process time, value-added time (VAT), non-value-added time (NVAT), number of staff available for each process, as well as the commute time from one process to another were noted for this study. Figure 2 depicts the process flow chart for the Level 2-3 patients in the ED as per the study conducted by Abeidi et al. (2018).</span>  

![](/Code0_251.jpg)
