---
date: "2016-04-27T00:00:00Z"
external_link: ""
#image:
#  caption: Photo by rawpixel on Unsplash
#  focal_point: Smart
#links:
#- icon: github
#  icon_pack: fab
#  name: Github
#  url: https://twitter.com/georgecushen
#slides: example
summary: 
#tags:
#- Deep Learning
title: Lean Methodology
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

Everything around us has been constantly changing at a very fast rate. The world, as we once knew it, isn't the same. Today the rate of population is very high in comparison to the available amount of resources around us. As such, it has become very important to focus on ways to get the most out of the available resources in the right way, without compromising on the essential needs for the future. This has been made possible by creating 'Sustainable Development' goals - an approach that the United Nations adopted in the year 2015, to focus on reducing and resolving environmental, economic and social issues.  
  
The Sustainable Development Report dataset for the year 2023 has been considered here. For the 17 different sustainability goals put forward by the United Nations, and these goals intended to be achieved by 2030, it would be quite fascinating to observe which countries or regions are leading today and which of those are lagging behind; whether the sustainable goals pertaining to different areas of environment, social and economy are related to one another; which goals are the ones that have been achieved by almost all the countries; how the different regions are performing, overall..the list of questions about this dataset can be never-ending!

With the world struggling to survive through so many major issues like depleting resources, injustice, wars, inadequate availability of daily necessities, pandemics, ever-growing population, etc., it would be quite interesting to explore this dataset to get to know, for a start, at which stage the world currently is, with respect to, making positive changes or reducing the damages that has been caused economically, socially and environmentally.
  
**2. Understanding the Data**
  
Published on the eve of the 2023 Paris summit for a new Global Impact, the dataset on "Sustainability Development Goals", is available for download on [Kaggle](https://www.kaggle.com/datasets/sazidthe1/sustainable-development-report/) and is annually updated.  

The core data on sustainable development in the dataset, which comes from the UN Statistics Division's Open SDG Data Hub, has been provided by the [SDG Transformation Center](https://sdgtransformationcenter.org/reports/sustainable-development-report-2023/). The SDG data in the data hub is collected annually from regional and national-level organizations of various countries. The collected data is obtained from different types of studies - cohort, case-control, cross-sectional, qualitative, to name a few. It is then compiled and verified globally by custodian agencies of the United Nations(UN). For example, UN custodian agencies like the World Health Organization(WHO) and United Nations Children's Fund(UNICEF) compile and verify the data related to waste water, drinking water, sanitation, hygiene at the global level.

© Citation: Jeffrey D. Sachs, Guillaume Lafortune, Grayson Fuller and Eamon Drumm, 2023.  

Authors: Sachs, J.D., Lafortune, G., Fuller, G., Drumm, E. (2023). Implementing the SDG Stimulus. Sustainable Development Report 2023. Dublin: Dublin University Press, 2023. 10.25546/102924 
        
  
It is to be noted that the UN DESA in collaboration with the entire UN Statistical System, along with international and regional agencies, comes up with an annual SDG report that contain interactive dashboards and a user-friendly interface. The report, in summary, showcases the existing gaps currently that are not helping to achieve the targets of the SDG goals set, urging countries and their people to double their efforts, and portraying that success toward achieving these goals is not impossible, thanks to present day's available technologies, resources and knowledge. The report can be found [here](https://unstats.un.org/sdgs/report/2023/).        
  
   
